import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getAllPostsForHome } from '../lib/api'
import Link from 'next/link'

export default function Home({ allPosts }) {
  const posts = allPosts.edges

  return (
    <div className={styles.container}>
      <Head>
        <title>Futurism Amplify App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://futurism.com">Futurism</a>
        </h1>


        <div className={styles.grid}>
          {posts.map((post) => <PostListing key={post?.node?.slug} post={post} />)}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Not Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
          &nbsp;
          <span>
            🤣
          </span>
        </a>
      </footer>
    </div>
  )
}

const PostListing = ({post = {}}) => {

  return (
    <Link href={`/${post?.node?.slug}`}>
      <a className={styles.card}>
        <h2>{post?.node?.title}</h2>
      </a>
    </Link>
  )
}

export async function getStaticProps() {
  const allPosts = await getAllPostsForHome()
  return {
    props: { 
      allPosts
    },
    revalidate: 60,
  }
}
